baseURL = 'https://codecraft-chronicles.netlify.app/'
languageCode = 'en-us'
title = 'CodeCraft Chronicles'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 30
  [[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'
