baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CodeCraft Chronicles'
theme = 'ananke'

[services.disqus]
  shortname = 'YOURSHORTNAME'

[params]
  commentoEnable = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
